name: act_thumbhash_example
description: Example for act_thumbhash
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  act_thumbhash: ^1.0.0-dev.1

dev_dependencies:
  lints: ^4.0.0