name: act_thumbhash

homepage: https://github.com/Act-App/Act-Thumbhash
repository: https://github.com/Act-App/Act-Thumbhash/tree/main/packages/act_thumbhash
issue_tracker: https://github.com/Act-App/Act-Thumbhash/issues

version: 1.0.0-dev.1

environment:
  sdk: ^3.6.0
resolution: workspace
dev_dependencies:
  image: ^4.0.0
  test: ^1.24.0